### ISSUE TITLE
Dragging/Dropping of values in the function position

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#1]
In the blocks for (star 50 "solid" "red"), I should be able to:
1) drag the 'star' value out of the block
2) drag any other block on top of the star literal, replacing it
3) double-clicking on it should make it editable

Use-case: the following (semantically-incorrect) code should be buildable: ((+ 1 2) 50 "red")
See "User Interactions > Dragging" and "User Interactions > Typing in a value" in the spec.

**Comment by pcardune** [comment]
(1) and (3) are now working.

Although question regarding (1). Once you drag the 'star' value out of the block, you are left with a syntactically incorrect piece of code. What should happen in this scenario?

**Comment by schanzer** [comment]
(50 "solid" "red") is syntactically valid, and should be allowed.
