### ISSUE TITLE
Improved Search Functionality

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#109]
up and down arrow are currently used to go from node-to-node, with hotkeys and modes for going from search-match-to-search-match. It may also be desirable to jump from function-to-function or struct-to-struct. Adding hotkeys for these is a mess.

We should instead implement a rotor (open/close by hotkey), which lets users change the behavior of the PageUp and PageDown arrows. Default is "all nodes", but other options include "matching string" and "Node type".

**Comment by sorawee** [comment]
@schanzer can we close this?
