### ISSUE TITLE
Block editors should expose a 'highlight' or 'marktext' API

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#11]
Depending on how much we want to align with CM (I'd image there's a big win for this), the Blocks Editor should also expose some subset of the MarkText API. 

Use case: a programmer has some code that calls cm.marktext(p1, p2, {css: "background: blue"}). If p1 and p2 correspond to the start and end of a block, that block should also take on that style rule.

**Comment by pcardune** [comment]
This sounds cool. Is this really an M1 feature though?

**Comment by schanzer** [comment]
It is - the structured error messages in WeScheme are a HUGE part of what sets us apart from everyone else, and we want to plug the block tool into WeScheme and preserve as many of the same behaviors. 

This could be implemented in a quick-and-dirty way in the interim, no? It could even be handled externally by a lower-level API, which just returns a node when given a starting/ending Pos. Let the WeScheme app figure out what to do with that node.

**Comment by pcardune** [comment]
ah, that makes sense. I didn't know that wescheme used that functionality.

**Comment by schanzer** [comment]
Go to Circles.wescheme.appspot.com, and evaluate the following code:
(star 50 "solid" "read")


Click on the links in the error message. Then convert two blocks, and evaluate again.
