### ISSUE TITLE
Use React properly

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#112]
Right now we're using React essentially as a replacement for Handlebars: we use it strictly for rendering nodes, without state or re-use. This problematic for two reasons:

1) Performance -- every time a subtree is changed, we nuke its entire DOM tree and re-render, even if only a small part of that subtree has changed. A quick trip to the React Developer toolbar shows lots of new React components being constructed all the time. This is Bad(tm)

2) Cleanliness -- it would be nice to represent the whole editor as one big Component, which tracks all the necessary state and deals with rendering appropriately.

Not sure what the step-by-step is here, because I don't actually *know* React well enough to provide smart guidance.

**Update 9/11/18**
@sorawee is hard at work on this, in the `new-react` branch. #137 , #156  are all part of this work.

**Comment by justinpombrio** [comment]
There was what looked like a good React tutorial on HackerNews the other day. 100% examples, actually starts from zero (i.e., vanilla JS).

[https://github.com/kay-is/react-from-zero](https://github.com/kay-is/react-from-zero)

**Comment by schanzer** [comment]
Tagging @lambdageek just so he's looped into any further discussion on this issue.

**Comment by sorawee** [comment]
@lambdageek do you need any help? I just joined the team and did React a little bit last month, so I might be able to help.

**Comment by lambdageek** [comment]
@sorawee By all means feel free to start from the fork in #121 (https://github.com/lambdageek/codemirror-blocks/tree/reactify) and hack on it.

**Comment by schanzer** [comment]
@lambdageek ,  is it preferable to have this as a branch rather than a fork? (Honest n00b git question)

if I split a branch off fix-tests, would you be willing to retarget you PR to that? Then I could merge the PR and we could all work off a branch in the main repo.

**Comment by lambdageek** [comment]
@schanzer sure that sounds like a good plan. just let me know the branch name to target

**Comment by schanzer** [comment]
Made a new `reactify` branch off master (which now includes some fixes to the test library). If you can push the PR to that, I'll merge and we can work off that.
