### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#113]
I get a variety of test failures when running tests on either my
laptop of my desktop. They both run Linux Mint with XMonad. None of
the keyboard commands being invoked conflict with anything in XMonad,
however.

I don't have a good sense of how to classify these, and whether there
are multiple issues or just one underlying issue.

    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node selection,  selecting a parent, then child should just select the parent  FAILED
    	Expected 'false' to be 'true'.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:550:59 <- spec/index.js:33:113773)
    	    at <Jasmine>
    	Expected 0 to be 1.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:553:47 <- spec/index.js:33:113950)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node selection,  alt-arrow preserves selection & changes active  FAILED
    	Expected 'false' to be 'true'.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:529:62 <- spec/index.js:33:112781)
    	    at <Jasmine>
    	Expected 0 to be 1.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:532:47 <- spec/index.js:33:112956)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node selection,  allow multiple, non-contiguous selection  FAILED
    	Expected 'false' to be 'true'.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:539:62 <- spec/index.js:33:113259)
    	    at <Jasmine>
    	Expected 'false' to be 'true'.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:540:59 <- spec/index.js:33:113323)
    	    at <Jasmine>
    	Expected 0 to be 2.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:542:47 <- spec/index.js:33:113425)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, should save a valid, edited node on blur FAILED
    	Expected true to be false.
    	    at <Jasmine>
    	    at webpack:///spec/blocks-test.js:588:43 <- spec/index.js:33:115193
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node activation, should proxy keydown events on the active node to codemirror FAILED
    	Uncaught TypeError: Cannot read property 'announcement' of undefined thrown
    	Expected spy execCommand to have been called with [ 'undo' ] but it was never called.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:380:36 <- spec/index.js:33:106736)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node activation, should proxy keydown events on the active node to codemirror FAILED
    	Uncaught TypeError: Cannot read property 'announcement' of undefined thrown
    	Expected spy execCommand to have been called with [ 'undo' ] but it was never called.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:380:36 <- spec/index.js:33:106736)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with node activation, cut/copy/paste should remove multiple selected nodes on cut FAILED
    	Expected 0 to be 2.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:404:49 <- spec/index.js:33:107479)
    	    at <Jasmine>
    	Expected '11 54' to be ' '.
    	    at <Jasmine>
    	    at webpack:///spec/blocks-test.js:408:39 <- spec/index.js:33:107613
    	Expected spy execCommand to have been called with [ 'cut' ] but it was never called.
    	    at <Jasmine>
    	    at webpack:///spec/blocks-test.js:409:41 <- spec/index.js:33:107652
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with whitespace, Ctrl-] should jump to the right of a top-level node FAILED
    	Expected 9 to be 7.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/blocks-test.js:659:26 <- spec/index.js:33:117222)
    	    at <Jasmine>
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class focusing, inserting mulitple nodes should put focus on the last of the new nodes FAILED
    	Expected '  (+ 99 88 77 1 2 3)' to be '(+ 1 99 88 77 2 3)'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:136:35 <- spec/index.js:25:63852
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class focusing, inserting a node should put focus on the new node FAILED
    	Expected '  (+ 99 1 2 3)' to be '(+ 1 99 2 3)'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:119:35 <- spec/index.js:25:63294

    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class focusing, deleting the multiple nodes should shift focus to the one after FAILED
    	Expected 0 to be 2.
    	    at <Jasmine>
    	    at UserContext.<anonymous> (webpack:///spec/focus-test.js:99:45 <- spec/index.js:25:62654)
    	    at <Jasmine>
    	Expected '(+ 1 2 3)' to be '(+   3)'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:102:35 <- spec/index.js:25:62768
    	Expected '0,2' to be '0,1'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:103:38 <- spec/index.js:25:62811

**Comment by schanzer** [comment]
Did you refresh the test harness browser? For me, a refresh is always required in order to get the tests to pass. Here's a screenshot I see pretty regularly:

![image](https://user-images.githubusercontent.com/77126/42218217-d9603484-7e95-11e8-835e-507547d6fb56.png)

**Comment by justinpombrio** [comment]
Yes: it has no effect. The console shows (like yours) that it disconnects, then re-connects. But then it prints the same 13 errors and the same "13 FAILED 242 SUCCESS" tally at the end.

**Comment by schanzer** [comment]
These are all keyboard-related errors. At least one of them is the backspace/delete issue, which is now fixed. I'm guessing certain keyboard events aren't firing because I haven't accounted for a Linux environment.

**Comment by justinpombrio** [comment]
Many of these were fixed by 0080ec2898bfa15fcca1a1d18608b038a7a41ea1 and 553151a4446b05abf16d6483595a91fb13e44dde. I'm looking into the other issues and will raise more specific bug reports with more details.
