### ISSUE TITLE
Delete vs. Backspace

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#114]
The Delete key on my laptop does not delete anything. This is because
of this line of code:

    const DELETEKEY=ISMAC? "Backspace" : "Delete";

which tries to guess whether my keyboard has a backspace or a delete
key based on whether the computer is a Mac or not. Unfortunately I
have Linux installed on a Macbook, so it gets it wrong.

Can we have the Backspace and Delete keys _both_ delete the selected
block? While my particular setup is unusual, it would be more robust
to have both keys do the same thing. And if someone on a standard
keyboard reaches all the way for the Delete key, I think their intent
is pretty clear.

Some resulting test failures:

    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class focusing, deleting the nth node should shift focus to n+1 FAILED
    	Expected '(+ 1 2 3)' to be '(+ 1  3)'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:88:35 <- spec/index.js:25:62235
    
    Chrome 65.0.3325 (Linux 0.0.0)
    The CodeMirrorBlocks Class focusing, deleting the last node should shift focus to the next-to-last FAILED
    	Expected '(+ 1 2 3)' to be '(+ 1 2 )'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:76:35 <- spec/index.js:25:61835
    	Expected '0,3' to be '0,2'.
    	    at <Jasmine>
    	    at webpack:///spec/focus-test.js:77:38 <- spec/index.js:25:61879

**Comment by schanzer** [comment]
Should be addressed by https://github.com/bootstrapworld/codemirror-blocks/commit/553151a4446b05abf16d6483595a91fb13e44dde

**Comment by justinpombrio** [comment]
Yes; I made exactly the same change earlier myself and it works. Closing now that it's in master.
