### ISSUE TITLE
Editor intercepts ctrl-shift-i

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#115]
The editor intercepts ctrl-shift-i, used to open the Javascript
console in Chrome. It should allow that to go through, unless there's
some good reason not to.

**Comment by schanzer** [comment]
This isn't us trapping it -- any key commands that the blocks editor doesn't understand get passed through to codemirror so IT can handle it. CM traps this by default.

A user can configure their CM instance to not catch these, but the blocks editor shouldn't dictate that.

**Comment by justinpombrio** [comment]
That makes sense, as long as by 'user' you mean 'language-specific editor author'. End users (programmers) certainly shouldn't be doing anything.
