### ISSUE TITLE
Spacebar shifts screen down

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#116]
Pressing Space shifts the screen down for me, in addition to selecting the current node. This is default browser behavior on Chrome (not sure about other browsers), but it should be disabled for the block editor if Space is going to be a command.

Stackoverflow has some suggestions on [overriding browser shortcuts](https://stackoverflow.com/questions/3680919/overriding-browsers-keyboard-shortcuts#3680946). It sounds like some of the more important ones can't be overriden (frankly, I think that's for the best), but Space might be.

**Comment by schanzer** [comment]
Fixed for now. A keymap overhaul is badly needed, so I'll open a separate issue for this.
