### ISSUE TITLE
Bug: Moving a literal from fn position to (empty) arg position

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#12]
Chrome 47/osx. Simplest way to reproduce:
1) Open the test page
2) In the (sum ...) block, drag the - function out of it's block, then drop it back in the original location.
Expected: no change
Actual: the character after the operator disappears, merging - and 1 to become '-1'.

(Probably related bug) To Reproduce:
1) Open the test page, and click the "WeScheme example" link
2) Scroll down to the (greet john) block, and drag john outside the block -> (greet) john
3) Drag 'greet' down into the whitespace within it's block

Expected: block is unchanged
Actual: greet is duplicated.

Repeating step 3 results in more weird location issues. Looks like an off-by-one error somewhere

**Comment by pcardune** [comment]
I'm not sure these are the same bug, but we can keep them together for now.

For the latter issue, I guess I have a broader question. If you have an expression like (foo), then presumably foo is in the operator position.  What does it mean to move foo from the operator position to the argument position? Like what does it look like in the code? If the block representation is always supposed to be an exact representation of the code underneath, then you can never have a block without something in the operator position.  Is that a problem? And if so, how do you think it should work?

**Comment by schanzer** [comment]
I think it's important to represent an empty application, so I'll need to modify the compiler to allow () to make it past the parsing stage. 

An empty application should have only one whitespace element inside of it, which is in the function position. 

Moving the function to the first whitespace element should be a no-op.
