### ISSUE TITLE
Test failure: stray click

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#123]
On my computer, this test case:

      describe('and specifically when editing it,', function() {
        it('should save whiteSpace on blur', function(done) {
          this.whiteSpaceEl.dispatchEvent(dblclick());
          setTimeout(() => {
            expect(this.trackQuarantine).toHaveBeenCalledWith("", this.whiteSpaceEl, jasmine.anything());
            let quarantineNode = this.trackQuarantine.calls.mostRecent().returnValue;
            expect(this.trackEditLiteral).toHaveBeenCalledWith(quarantineNode);
            let quarantine = quarantineNode.el;
            let trackOnBlur = spyOn(quarantine, 'onblur').and.callThrough();
            let selection = window.getSelection();
            expect(selection.rangeCount).toEqual(1);
            let range = selection.getRangeAt(0);
            range.deleteContents();
            range.insertNode(document.createTextNode('4253'));
            expect(quarantine.innerHTML).toBe('4253');
            quarantine.dispatchEvent(blur());
            setTimeout(() => {
              expect(trackOnBlur).toHaveBeenCalled();
              expect(this.trackSaveEdit).toHaveBeenCalled();
              expect(this.cm.getValue()).toBe('(+ 1 4253 2) (+)');
              expect(this.blocks.hasInvalidEdit).toBe(false);
              done();
            }, DELAY);
          }, DELAY);
        });

fails with this error message:

    Chrome 67.0.3396 (Linux 0.0.0)
    The CodeMirrorBlocks Class events, when dealing with whitespace,
    and specifically when editing it, should save whiteSpace on blur FAILED
	Expected '' to be '4253'.
	    at <Jasmine>
	    at webpack:///spec/blocks-test.js:712:41 <- spec/index.js:25:105779
	Expected '(+ 1  2) (+)' to be '(+ 1 4253 2) (+)'.
	    at <Jasmine>
	    at webpack:///spec/blocks-test.js:717:41 <- spec/index.js:25:105940

Here is what seems to be happening:

1. The doubleclick event on the whitespace element goes off.
2. This correctly calls `insertionQuarantine`.
3. This correctly determines that a whitespace element has been chosen, and looks like it replaces the whitespace element with a new quarantine/literal/white-space element.
4. `insertionQuarantine` calls `editLiteral` with a delay.
5. `insertionQuarantine` and the doubleclick event complete.
4. After a delay, the call to `editLiteral` happens. `editLiteral` continues adjusting and focusing the quarantine element, and gives it an `onblur` handler.
5. `editLiteral` completes.
6. Suddenly, out of nowhere, the `onblur` handler fires.
7. The `onblur` handler calls `saveEdit`, which removes the quarantine element and replaces it with the original "blocks-drop-target blocks-white-space" element.
8. Since the edit has been cancelled by `onblur` before the test has even begun, it's not surprising that the test fails.

The issue is the `onblur` event. Where is it coming from? It happens after the doubleclick event finishes, and after the `editLiteral` call (which is behind a `setTimeout`) finishes.

It's coming from a `singleclick` event. I'm not sure why this would fire. When editing in the browser, and double clicking, two single click events get fired _before_ the double-click event, so it would make _some_ sense for JS/Karma to simulate single clicks when dispatching on a double-click event. But this single click is coming _after_ the double click, so I'm not sure where it's coming from.

The other remaining test failure seems to be caused by the same issue: a stray single click.

**Comment by schanzer** [comment]
I added a log to saveEdit (just before the call to parse) and to nodeEventHandler. When logging the whole test interaction to the console, I see the following sequence of (annotated) events:

`Switching to Block Mode` // blocks editor enabled
`dblclick` // test harness doing what it should, triggering calls to insertionQuarantine and editLiteral
inserting . Use Enter to save, and Shift-Escape to cancel // editLiteral reports correctly
click // I truly don't know what this is from -- so I hear you on the stray click event..but it does NOT trigger saveEdit!
blur // triggers the call to saveEdit
trying to parse "4253" // ok! we're in saveEdit!
committing change. saving focus at // saving the edit...
inserted  "4253 // correctly inserted
click // render triggers a click event when all is said and done.

This sequence is _identical_ whether the JS console is open or closed, save for the "4253" being the empty string when it's open. I don't know where that click is coming from, but I'm not convinced it's the culprit.

**Comment by justinpombrio** [comment]
Here is what I see. It's consistent with what you see. "?thing" means the beginning of thing, and "/thing" means the end of thing. The very last log entry here, "?testTimeoutStart" is when the `setTimeout()` in the test activates. So all of this is happening before the main body of the test runs at all. In particular, it's all happening before the test tries to insert "4253".

```
LOG: 'Switching to Block Mode'
LOG: 'starting animation took: 0.013ms.
0.008ms (61.54%) of that was for Rendering 1 roots'
LOG: 're-render time: 0.008ms'
LOG: '?ws', <span class="blocks-drop-target blocks-white-space"></span>
LOG: '?dblclick'
LOG: '?handler', 'dblclick'
LOG: '?dblclick/ws'
LOG: '?insertionQuarantine'
LOG: '/insertionQuarantine'
LOG: '/dblclick/ws'
LOG: '/handler'
LOG: '/dblclick'
LOG: '?editLiteral'
LOG: 'inserting . Use Enter to save, and Shift-Escape to cancel'
LOG: '/editLiteral'
LOG: '?handler', 'click'
LOG: '?blur'
LOG: '?saveEdit'
LOG: 'trying to parse ""'
LOG: 'commiting change. saving focus at ', '0'
LOG: 're-render time: 0.003ms'
LOG: 'inserted  '
LOG: '/saveEdit'
LOG: '/blur'
LOG: '/handler'
LOG: '?handler', 'click'
LOG: '/handler'
LOG: '?testTimeoutStart'
Chrome 67.0.3396 (Linux 0.0.0) The CodeMirrorBlocks Class events, when dealing with whitespace, and specifically when editing it, should save whiteSpace on blur FAILED
	Expected '(+ 1  2) (+)' to be '(+ 1 4253 2) (+)'.
	    at <Jasmine>
	    at webpack:///spec/justin.js:121:41 <- spec/index.js:25:98133
Chrome 67.0.3396 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (1.789 secs / 1.578 secs)
npm ERR! Test failed.  See above for more details.
```

> I truly don't know what this [single click event] is from -- so I hear you on the stray click event..but it does NOT trigger saveEdit!

It looks to me like the single click is triggering the blur event is triggering the saveEdit.

**Comment by schanzer** [comment]
OK, I'm convinced that you're right. :) This definitely looks race-y, since I can see the click when I re-run the tests with the console open but it doesn't cause the problem. Until we can either track down the click or find an update to Karma that fixes this, I think we need to leave this issue open and those tests commented.

Thanks for helping to track this down!

**Comment by schanzer** [comment]
I'm going to close this, since (1) the entire codebase has changed and (2) we're in the process of rewriting many tests. I suspect we'll open some new issues for tests that are still stumping us.
