### ISSUE TITLE
Clean up all `var`s

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#124]
We have webpack. Probably should use `let` and `const` everywhere for sanity, and let webpack transforms them to `var` for us.

**Comment by schanzer** [comment]
Totes. There's at least one area in the codebase where `var` is required  (`assignClonePostion()` in Renderer.js), but otherwise we should definitely take a cleanliness pass over this.

**Comment by schanzer** [comment]
Given how much has been rewritten for `new-reactify`, I'm labeling this as fixed in that branch.
