### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#125]
Right now the wescheme bundle has a lot of stuff it doesn't need: the entire wescheme compiler and codemirror. These should be removed from that bundle.

Similarly, we don't need EVERY babel-polyfill for every bundle. We should cherry-pick on the ones we need (regenerator and some of the array methods?).

**Comment by sorawee** [comment]
Also, `webpack-bundle-size-analyzer` and `babel-preset-stage-1` should be devDependencies so that they do not get bundled.

I'll clean this up along with other package cleanup.

**Comment by schanzer** [comment]
I believe there are now babel settings that let you specify which browsers you support, and babel automatically chooses the polyfills you need. Aside from `regenerator-runtime`, we're pretty much 100% compliant with IE10+ and all the Chromes, FF and Safari -- which means the rest of the polyfills can almost certainly be removed.

Getting CM out of the bundle is something I've made quite a few attempts at. If you can get this one working, it would be quite an improvement right away.

**Comment by sorawee** [comment]
Yes! That's `babel-preset-env`. We should replace `babel-preset-es2015` with it.

**Comment by schanzer** [comment]
Moved those to devDependencies in 9df559aa1f282779dac09bebd30ea41d10883807

**Comment by schanzer** [comment]
Upgraded to babel7 and slimmed down the polyfills. Not much savings here, but at least we're more future-proof as browsers evolve.

The big wins are still going to come from removing CM and the WeScheme compiler from the bundle

**Comment by schanzer** [comment]
CM has been removed, and serious tree-shaking has dropped the bundle size to under 600kb! Closing this issue now, since all the remaining fruit to be picked is going to be in the language-specific repos.
