### ISSUE TITLE
Bad speaking of literal elements

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#130]
In the WeScheme example, click on `"hello"`. Here's the read text:

> Has comment, string
> Tree item, multi select, not selected, 2 of 21
> Use enter to edit.

The word "hello" doesn't even get read!

**Comment by schanzer** [comment]
That's odd - because `"hello", a string` is what gets dumped to the console and to the screenreader. Confirmed working on Safari, Firefox, and Chrome on OSX, as well as Chrome/FF on Windows 10 with NVDA.
