### ISSUE TITLE
Separate Bootstrap out cleanly

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#132]
Some components right now use Bootstrap implicitly (e.g., Toolbar, Search). However, the style is loaded in example pages, and this would break badly if clients don't include Bootstrap.

**Comment by schanzer** [comment]
To be clear, this is _just_ the bootstrap css file, yes?
Moving forward, I'd really like to include only the rules we care about. I don't know if CSS compilers do dead-rule elimination, but I genuinely worry about including all of the Bootstrap CSS rules if we're only using a small fraction.

**Comment by sorawee** [comment]
Yes.

There is a way to include only few rules that we care about. Ironically, to do so, we need to install the full bootstrap libraries and then add some customization to choose only what we want.

**Comment by schanzer** [comment]
Fabulous. As long as we're doing the right thing in our build system, I say go nuts. :)

**Comment by schanzer** [comment]
Currently the only use of Bootstrap is in `less/blocks.less`. Removing that line entirely appears to have no effect on the editor. @sorawee , are we now free to remove it?

**Comment by sorawee** [comment]
Really? It _should_ have a visible effect, and _definitely_ have a visible effect on the search box.

**Comment by schanzer** [comment]
For now it looks like Bootstrap is _only_ loading the CSS files, and those are done dynamically. I think this is fine to close for the time being. We can always revisit if we want to inline the specific style rules we care about.
