### ISSUE TITLE
Typing too fast creates multiple elements

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#139]
Typing `1` `2` `3` consecutively should create a new literal with content `123`. However, if we type them too quickly, we will get 3 literals: `3`, `2`, and then `1`

**Comment by schanzer** [comment]
@sorawee , this timeout voodoo feels really weird. Does this commit address the issue for you? It's possible that we should be intercepting a different event (`keydown` is the next thing I'd try)

**Comment by sorawee** [comment]
Unfortunately, it still happens :(
