### ISSUE TITLE
Overlapping line

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#142]
![2018-08-13-163525_891x423_scrot](https://user-images.githubusercontent.com/9099577/44024293-15944ad4-9f17-11e8-8c92-e76ea1dfa401.png)

Linux, Firefox 61

**Comment by schanzer** [comment]
I can reproduce this on FF/OSX. Interesting. It looks like the line-height for the empty line preceding the block is being set to zero, causing it to collapse - but the gutter doesn't, so it bleeds into the next one.

**Comment by schanzer** [comment]
Fascinating - CodeMirror generates subtly different DOM for FF and Chrome! 

Here it is on FF: 
![image](https://user-images.githubusercontent.com/77126/44109471-28d48d2a-9fcb-11e8-9f16-a5c5e0321b65.png)

Compare to Chrome:
![image](https://user-images.githubusercontent.com/77126/44109492-36daa31e-9fcb-11e8-8ee0-86a579d7aba4.png)

Manually adding that padding in Firefox fixes the issue. I believe this comes from [this line of code in CM](https://github.com/codemirror/CodeMirror/blob/master/src/line/line_data.js#L67).
