### ISSUE TITLE
Sliding arguments

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#145]
Not sure if this is qualified as a bug. But I believe there's something problematic with it.

Consider a block corresponding to `(f 1 2 3)`. If I empty `f` to empty string, `1` will replace the function position. It makes sense textually, but makes no sense at all in a tree.

Even if this is not considered a bug, UI-wise, it's kinda bad because _it is very hard to add `f` back_ (if we have `(e0 e1 e2 e3 ... en)` for arbitrary `e0`, ..., `en` and we take `e0` out, now we will have `(e1 e2 e3 ... en)`. To add `e0` back, we must first add `e0` before `e2`. Then, drag `e1` to be between `e0` and `e1`. This will slide `e0` back to the function position)

**Comment by schanzer** [comment]
This doesn't directly address the UI issue you're describing, but: you can insert to the left or right of the value in the function position.
![untitled](https://user-images.githubusercontent.com/77126/44146328-13fb5b80-a05d-11e8-88b1-39c7c3273e95.gif)

But as for the UI -- I'm not convinced this is necessarily a bad thing. The tree is based on the text, and we _do_ want some of the text behavior to leak through here (this goal is markedly different from Snap!, which explicitly bends over backwards to hide any notion of a textual representation).

We could consider this a sub-problem of the block-sugaring work @justinpombrio told me about, which basically adds a layer of sugar that is exclusive to blocks and allows for blocks with explicit "holes" that must be filled. I have a strong sense that block sugar is the general-purpose way of handling things like this.

**Comment by schanzer** [comment]
Note: Tara totally agrees with you, @sorawee !!! She found this really counterintuitive.

**Comment by sorawee** [comment]
Well... at this point:

- Making it intuitive would need a total rewrite of the patching algorithm and a lot of restructuring. 
- The "intuitive" way means we want a proper structural code editor and not text-based one. 
-- This requires  additional features from parsers (say I remove `+` from `(+ 1 2)`. Ideally I would want this to be `(??? 1 2)`, but do parsers recognize `???`?). 
-- It means there is one fewer reasons to use CodeMirror in the block mode.

There's actually a simple fix: do not distinguish the function arguments and function position. Distinguishing them (which is what we do right now) makes an expectation that our editor is structural. If we don't, then users won't expect that. 

But then again, the above fix would make blocks deviate from circles of evaluation.

CC: @justinpombrio

**Comment by sorawee** [comment]
I guess another point would be, from blind users' POV, is this confusing? I think I find it unintuitive because the graphical interface is suggestive (as I mentioned above), but for those who can't see the graphical interface, will it still be unintuitive?

**Comment by justinpombrio** [comment]
The fundamental issue here seems to be that certain edits look relatively benign from a block perspective, but are malformed from a text perspective. For example (stealing some of your examples):

1. Inserting "hello" to the left of "+", producing ("hello" + 1 2).
2. Dragging "+" away, producing (1 2)
3. In Pyret, replacing "+" with `f`, producing `1 f 2`

I also noticed this while testing drag-n-drop: almost all possible acts of dragging produce ill-formed code.

@schanzer that's not quite what "sugar blocks" are about. But I like your high-level idea: how about we disallow _particularly_ ill-formed edits? For example:

1. No drop targets to the left or right of "+".
2. You can't drag "+" away. Or alternatively you can, but it doesn't delete the original.
3. Check edits against a regex that only matches Pyret binops. Or maybe that's too much, and we just allow this bad edit.

**Comment by justinpombrio** [comment]
This is fixed in the [editing-syntax](https://github.com/bootstrapworld/codemirror-blocks/tree/editing-syntax) branch. There are no longer drop targets to the left or right of `+`. If you drag the `+` away, it will be replaced with `?`.
