### ISSUE TITLE
Sanitize input for quarantines

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#147]
One downside of `contenteditable` is that arbitrary html is allowed and it will be displayed (until changes are committed). The content should in fact be sanitized immediately. A more proper way might be to use `<input type="text" />` instead

![2018-08-18-135153_2560x1440_scrot](https://user-images.githubusercontent.com/9099577/44296772-33846c00-a2ef-11e8-9799-48ef9bc54571.png)

**Comment by schanzer** [comment]
Agreed. This will require some extra work on insertionQuarantines, however, since currently we just abuse the normal rendering/react infrastructure to make a fake literal node.

**Comment by sorawee** [comment]
`<input type="text">` has a downside being that it won't dynamically fit to the content. And the *only* way to make it the box fit the content is to use JavaScript, which is very surprising to me (https://leaverou.github.io/stretchy/, https://github.com/JedWatson/react-input-autosize). It also will have white background and the usual box border, though these can be removed using CSS.

**Comment by schanzer** [comment]
What about TEXTAREA? And worse comes to worse, perhaps sanitizing is the best option anyway...

**Comment by schanzer** [comment]
Did some experimenting with TEXTAREA: it's not going to do what we want. I'll take a crack at cleaning up the quarantine code, and sanitizing the input text

**Comment by schanzer** [comment]
@sorawee how did you get those DOM nodes to show up in the quarantine? Was it copy/pasting, or something else?

**Comment by schanzer** [comment]
Yep, that’s exactly what I’m doing. Take a look at the the `input-quarantine` branch, which includes a bunch of quarantine cleanup and sanitization.

**Comment by schanzer** [comment]
Fixed in d32316d692f5d60ff514822bb6cb5666d68f5990
