### ISSUE TITLE
Unicode string display should be supported

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#148]
Foreign languages are unreadable otherwise.

![2018-08-18-141015_906x135_scrot](https://user-images.githubusercontent.com/9099577/44296849-7d218680-a2f0-11e8-8cd7-829e6e36deff.png)

Note that this is a problem only with string literal. Unicode variable name, for example, can display fine.

**Comment by schanzer** [comment]
Fixed by 3bdfa8f2795f1481c700125690a23c2396483d8f
