### ISSUE TITLE
[Bug] Dragging a function onto argument works inconsistently

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#16]
Chrome/OSX:
1) Open wescheme example, and add a new expression (+ 1 2 3 4)
2) Drag the function on top of 4

EXPECTED: 1 becomes the function, whose arguments are 2 3 +
RESULT: No-op

The same happens if you try to replace the 3, BUT replacing the 1 and 2 works perfectly

**Comment by schanzer** [comment]
It looks like getLocationFromEl is returning null for everything (possibly because we're no longer setting 'line' and 'ch' attributes on anything anymore?). As a result, we're using cm.coordsChar to find the destination character, which definitely seems to be broken -- in the example above, it's giving totally totally bogus results, which trigger a no-op.

**Comment by schanzer** [comment]
@pcardune any objections to me merging and closing?

**Comment by pcardune** [comment]
Left some notes for you. Thanks for waiting. (I was in the wilderness)

**Comment by schanzer** [comment]
Not sure if PR comments send notifications, so I'm poking here.
