### ISSUE TITLE
Need a better way to clean up whitespace

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#166]
Consider 

```
(x y)
```

After removing `y`, I would expect to see `(x)`, but the result is instead `(x )`.

On insertion, we have a hack called `willInsertNode` to insert whitespaces, but the same hack wouldn't work for deletion.

**Comment by schanzer** [comment]
Would Justin’s Pretty-Printing library save us here? Since it dictates what the textual representation should be anyway, it will tell us how whitespace should be transformed

**Comment by sorawee** [comment]
It might. I should merge master to mine and see if it helps.

**Comment by schanzer** [comment]
@justinpombrio does your algorithm do the right thing here?

**Comment by justinpombrio** [comment]
Yes. Here's the flow:

- Start with the text `(x y)`.
- Switch to block mode.
- Delete `y`. (space, delete)
- Switch to text mode.

At that point, I see `(x)`.
