### ISSUE TITLE
New-Reactify Merge blockers

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#172]
- [x] Make moar tests pass
- [x] Optimization
- [x] Allow editor to be embedded (partially done)
- [x] Insert-right (`Ctrl-[`) and insert-left (`Ctrl-]`) are broken for non-top-level nodes
- [x] Drag and drop on top level
- [x] A newly-loaded editor should default to having the first node active.
- [x] Activating a block and then arrow-navigating to the next block should show the orange focus ring. Currently, it doesn't. Looks like we either need to wrap `node.element.focus()` in a timeout, or find some other way of getting React to set `activeElement` after a reconcile is complete.
- [x] Inserting whitespace messes up text marking in CM. For example: inserting a newline between two top-level blocks
- [x] Distinguish "our" and "their" markers
- [x] Get search working again
- [x] Get toolbar working again

**Comment by schanzer** [comment]
Address "our" v. "their" markers via e216b8fb57175b589c3549e3cb868f528e7b175b

**Comment by justinpombrio** [comment]
It looks like Oak added top-level drag-and-drop with [this commit](https://github.com/bootstrapworld/codemirror-blocks/commit/c4e9c504f36ac721ebef1522134bb76e8f852ceb).

**Comment by schanzer** [comment]
Yep. I was going to hold off until he implemented the custom drag layer, but I think it’s fine to check the box for now

**Comment by schanzer** [comment]
The start of embedding support was added in https://github.com/bootstrapworld/codemirror-blocks/commit/c9e1f7ce58ead23631700484d92e89dcb0572395.
