### ISSUE TITLE
Overlapping Line Numbers

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#175]
This code:

    ; comment
    (+ 1 2)

is rendered like this, with overlapping line numbers in the gutter:

![image](https://user-images.githubusercontent.com/434946/50719078-41037e00-1065-11e9-879b-4ed27410428e.png)

Presumably this is because line 1 isn't being skipped because it isn't empty (it contains a comment), but has height 0 because there's nothing there to render. I don't yet know what determines whether a line is skipped and what its height is, though.

This is particularly an issue in `new-reactify-with-pretty`, since it normalizes comments to appear on the previous line, thus triggering this issue for most comments.

**Comment by sorawee** [comment]
I thought we fixed this. See #142

**Comment by justinpombrio** [comment]
This specifically involves comments. I suspect that this was fixed for ordinary code, but not for commented code?

**Comment by justinpombrio** [comment]
Fixed by ddc5af5. (This was a regression of #142, the fix was the same).
