### ISSUE TITLE
Lost Comments

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#180]
This code:

    (+ 1
    2) ; comment

when parsed, produces an AST with no comment.

This results in some bugs when dragging blocks. For example, if you drag an uncommented block into a commented block, then the comment will escape the block and render as text, and then vanish after switching to text mode.

**Comment by schanzer** [comment]
Seems like a bug in WeSchemeParser - I'll look into it.

**Comment by schanzer** [comment]
Fixed in https://github.com/bootstrapworld/wescheme-js/commit/cf673eb100cc9b215ead7e1872da9654ef9f2dfb

**Comment by justinpombrio** [comment]
Not quite - this seems to fix `;` comments, but not `#|...|#` comments in that position.

**Comment by schanzer** [comment]
Are you sure? I just tried
```(+ 1
2) #| moo |#```, and the comment was visible in blocks mode 
![image](https://user-images.githubusercontent.com/77126/51578321-274a9f00-1e8b-11e9-808d-918f0758864e.png)

**Comment by justinpombrio** [comment]
That's odd.

When I copy-paste that code into text mode, I don't see the comment after switching to blocks mode. And when switching _back_ to text mode, it's gone. I'm on `new-reactify` and just pulled.

**Comment by justinpombrio** [comment]
This is fixed, though its hard to see the change. Here are the steps I went through for it:

1. update `package-lock.json`,
2. `npm install wescheme-js`,
3. clear browser cache
