### ISSUE TITLE
We should announce undo/redo actions

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#184]
This requires adding something like `history : {undo: [], redo: []}` to the editor state.

- Whenever `commitChange` is called, we add the announcement text to the `undo` history and clear the `redo` history.
- Whenever an `undo` action is initiated, we pop the announcement off the history, say "undo _announcement_", and push the announcement onto the `redo` history.
- Whenever a `redo` action is initiated, we pop the announcement off the history, say "redo _announcement_", and push the announcement onto the `undo` history.
- NOTE: we should also think through how the history state is effected when edits/undo/redo is called programmatically on the raw CM instance 

(see https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/blocks.js#L114, https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/blocks.js#L212-L213, and https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/blocks.js#L957-L969)

**Comment by justinpombrio** [comment]
It sounds like this would be _in addition_ to the existing undo/redo mechanisms? If so, we should:

1. Make damn sure this behavior lines up with existing undo/redo behavior, because it's going to be very confusing if they get out of sync, and
2. Give this state a more precise name to make it clear that it isn't storing the _full_ undo/redo  history. E.g. `history: {undo-announcements: [], redo-announcements: []}`. Or `undo-annoucement-history: {undo: [], redo: []}`.

**Comment by schanzer** [comment]
I dig your renaming. And yes, this is a layer that just tracks announcements, and tries to keep them in sync with CM's native undo/redo mechanism.

100% agree on the complexity - this is something we had to deal with in `master`. Back then it was easier, since we just listened to CM's onChange event and took that as gospel. In `new-reactify`, it's definitely more complex. One thing we'll need to do, for example, is wrap content-setting methods (#162) to make sure that the main onChange event is never called after an invalid edit. 

Once we know that all valid edits will succeed, we can preserve the invariant that every call to `onChange` will result in an `announcement-history` change: if the origin is undo/redo, we push/pop the history arrays. Otherwise, we nuke `redo` and push something onto `undo`.

**Comment by justinpombrio** [comment]
We now keep undo/redo stacks, and (hopefully!) keep them in sync with CodeMirros' undo/redo history. So this change should be pretty easy now. We need to:

- [ ] Undo/redo is currently handled in `src/ui/BlockEditor.js:handleChanges`. This is silly, as there's already a file for actions like this called `src/actions.js`. Make `undo()/redo()` functions there and call them from `handleChanges`.
- [ ] Right now, we're only storing the focus (which node is highlighted) in our undo/redo stacks. We also need to store an announcement there. The undo/redo stacks are appended to in `src/edits/commitChanges()`. (See `src/reducers.js` for more context; that's our Redux store.) `commitChanges` will need to also create and store an undo announcement and a redo announcement.
- [ ] Finally, the newly minted, `undo()` and `redo()` functions in `actions.js` should speak the announcements.

**Comment by schanzer** [comment]
Closed by 461c2c97a36bfe04017c5c359b6c58d459ac0190. Nice work, @ds26gte !
