### ISSUE TITLE
You should be able to collapse/uncollapse with the mouse.

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#189]
Per Shriram:

> I don't understand. It sounds like I can't open things up using the mouse? Pro-keyboard is great, but anti-mouse is … weird?

**Comment by schanzer** [comment]
Any objection to using dblclick for this, for now?

**Comment by schanzer** [comment]
I'm going to close this for now, unless we get stronger feedback that a button for collapsing is needed.
