### ISSUE TITLE
Shortcut proposal: expand all descendants of current node

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#192]
It would be useful to say "fully-expand all of this node's offspring". 

`Right-Arrow` means "expand the current node"
`Shift-Right-Arrow` means "expand every single node"

Perhaps "Shift-Alt-Right-Arrow" would suffice for this?

**Comment by justinpombrio** [comment]
To be clear, this means that if you have the ast:

    (A (B C) (D (E F)))

and `B` and `E` are collapsed:

    (A (B...) (D (E...))

and the cursor is at `A`, then Shift-Alt-Right-Arrow should expand both `B` and `E`?

**Comment by schanzer** [comment]
Yep

**Comment by schanzer** [comment]
Implemented in f5e8f2432675a47f23918268cfcbbd98462380fb
