### ISSUE TITLE
Collapsed state is sometimes lost when dragging between generations

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#193]
Consider:
```
(if (> x 0) a (+ 1 2))
```

Suppose the two child expressions are collapsed, and the user drags `(> x 0)` out to the top-level. The resulting new root will be expanded, because our patching algorithm can't identify it as being the same node as it was before.

I suspect we can't fix this without adopting a N^3 patching algorithm, but I want to at least mark the issue so we can discuss.

**Comment by justinpombrio** [comment]
I can imagine a complicated fix for this that doesn't involve changing the patching algorithm much. When dragging, we can get (i) the location that the block was dragged to, and (ii) the location that it was dragged from. We could then _hint_ to the patching algorithm that the node at the `dragged-from` location in the old ast is the same as the node in the `dragged-to` location in the new ast.

**Comment by schanzer** [comment]
I think hinting won't get us far enough. If we can't provide a consistent experience, it might be worse than a merely annoying experience. Oak's algorithm builds up list of "seen" node hashes by walking the tree in a particular way, and if it encounters a new node that hasn't been seen before it will generate a new ID _no matter what_. 

I think we can do better, however, and we have two ways of doing it:
1. In `commitChange`, look for a situation where the `changes` array contains two consecutive changes in which the deleted text exactly matches the inserted text. In this circumstance, it passes an extra argument to `patch` that declares this to be a MOVE operation and adds some extra info (like the ID of the node that was moved). `patch` then does something specific with this information, ensuring that we always do the Right Thing.

2. In `dropNode`, we abuse CM's `origin` parameter, and encode special info in the `replaceRange` calls that gets passed to the `change` event that allows us `commitChange` to pass it on to `patch`.

I really prefer the first solution, if it seems viable -- it's less hacky, and it buys us some efficiency and correct behavior even if someone moves the text  _programmatically_.

**Comment by schanzer** [comment]
Update: I've done an experiment (see WIP-new-reactify-with-drag branch) that seems to do the right thing, but haven't had a chance to test more fully. Putting it out there to share ideas.

The gist is that we iterate through the `changes` array and look for DnD operations. If we see one, we patch the AST right then and there using the drag info (necessary in order to handle a `changes` sequence that includes multiple DnDs), and then keep iterating. If the most-recent-patch still hashes to a different value after we've gone through all the `changes`, we patch it against `newAST`. Otherwise, we just return what we have.
