### ISSUE TITLE
`setCursor` does not work

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#197]
The `SET_CURSOR` action does not work. Not only does it not set the CodeMirror cursor, it also seems to corrupt the state of the editor, as you can experience firsthand if you try pressing the `End` key.

This seems to be the cause of the three tests in `spec/activation-test.js` that fail.

**Comment by schanzer** [comment]
In blocks mode, clicking anywhere at the top level fires a `SET_CURSOR` event, which does seem to update the state correctly. Can you post steps to reproduce?

**Comment by schanzer** [comment]
Now that we're investigating other, less-invasive methods to make CM updates cheaper, this can be closed.
