### ISSUE TITLE
Drag and drop doesn't always respect comments

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#199]
1) Try dragging a block UP onto a root literal, replacing it. Then try dragging that same block DOWN onto some top-level cursor position. You’ll find that there’s an error generated from `dnd.js`
2) That’s because `dnd.js` iterates through block markers, looking for their DOM elements…and after replacing that first root literal, the marker lives on but the DOM is gone.
3) This is fixed by adding `componentWillUnmount() { this.mark.clear(); }` to the `ToplevelBlock` class
But now, upon replacing that root literal, we get a dangling comment!

**Comment by justinpombrio** [comment]
Fixed by b591938f62b3844a5a99b32b0d81c3791564f21e.
