### ISSUE TITLE
Do we need editorChange?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#200]
Right now we handle non-CMB-originating operations (`codeMirror.js :: commitChange()`) differently from CMB-originating ones (`BlockEditor.js :: editorChange()`). Why the second codepath? Now that we've added drag-and-drop detection to one codepath,  things like _undoing_  a DnD operation have wonkier behavior.

The more things we add to `commitChange`, the more these paths will diverge. We not just route everything through one path?

**Comment by justinpombrio** [comment]
This has changed now that the `editing-syntax` branch is merged. Non-CMB edits now get handled via two event handlers:
- Our `on("beforeChange")` handler (in `BlockEditor`) will call `speculateChanges()`, and if the chang results in a parse error then we'll cancel it.
- For sets of changes that make it through, our `on("changes")` handler will call `commitChanges()` and actually make the changes.

This results in a rather long sequence of events for non-CMB changes, but it means that we can handle arbitrary CM events.
