### ISSUE TITLE
Cannot select `if` drop targets

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#202]
To reproduce:

1. Start with an `if` expression. The one in the default program will do, or just use `(if true 1 2)`.
2. Try to double-click to edit one of the if's drop targets. Notice that you can't.
3. (Optional) now edit a different part of the `if`, and see that the world has turned to madness.

This appears to have been caused by 694cfed8988793b24c284d405963c6354e74ada7.

My immediate guess is that the heuristics for telling when a node has changed are failing here.

**Comment by schanzer** [comment]
@justinpombrio this appears to be fixed after your PR (I can't reproduce it). Are you satisfied that it can be closed?

**Comment by justinpombrio** [comment]
Yup! Fixed by b48b4deb09a2685ec9805.
