### ISSUE TITLE
Bad focus with top-level edits

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#205]
1. Replace the program with `(+ 1 2)`.
2. Switch to block mode.
3. Use the mouse to place your cursor after the block.
4. Press enter to insert a newline.
5. BUG - the focus is now on the `2`, while it should instead remain on the toplevel cursor.
6. "Edit" the `2` by pressing `Enter` twice.
7. Use the mouse to select the whole block.
8. Press down 3 times.
9. BUG - this should navigate to the `2`, but instead it gets stuck at the `1`.

**Comment by schanzer** [comment]
@justinpombrio, if by "select the whole block" in Step 7 you mean "create a selection range in CM that encompasses the block", this is still an issue. If you just mean "click on the block", it's resolved.

**Comment by justinpombrio** [comment]
Confirmed that this is fixed.
