### ISSUE TITLE
Comments and Dragging Bug

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#209]
1) Open the default editor, with `ast-test.rkt` loaded, and switch to block mode
2) Drag the `if` expression from line 13, and drop it after the `print` expression on line 7

EXPECTED: the if expression (and the associated comment) is pushed onto the next line
ACTUAL: the if expression is pushed to the next line, and the text of comment stays on line and is un-blockified

**Comment by justinpombrio** [comment]
Yikes! Apparently I had tested the `if` onto the `if`, the `print` onto the `if`, but not the `if` onto the `print`, and somehow that behaves differently.

**Comment by schanzer** [comment]
Looks like a great new test case? :)

**Comment by schanzer** [comment]
@justinpombrio interestingly enough, this now fails with a `BEEP!` (which is still way better than what it used to do)

**Comment by schanzer** [comment]
Whoa...it's actually quite another bug. Closing this and opening a separate issue

**Comment by justinpombrio** [comment]
I'm seeing two separate issues here. One is that drag-and-drop to the toplevel fails with a BEEP (#226). That tends to partly go away after interacting with the editor a bit, letting you do _some_ top-level dragging. Once you can, this issue (the leaking comment) still appears.

**Comment by justinpombrio** [comment]
Actually fixed by f82c43cb175cf3df77c7.
