### ISSUE TITLE
Focus lost after inserting newline

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#212]
1. Click to get a toplevel cursor after a block.
2. Press `enter` to insert a newline.

The focus should remain on the toplevel cursor. Instead, focus jumps to the block above the edit.

**Comment by schanzer** [comment]
This is the same issue as #205 - every change naively calls `activate`. We need to check to see if the editor state has a cursor set, and only call active if it doesn't. A one-line fix gets us most of the way there, but there are some interesting corner-cases where we need to be more sophisticated.

**Comment by schanzer** [comment]
Fixed by 582bdd5
