### ISSUE TITLE
Focus lost when deleting a toplevel line

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#216]
(Similar to #212, but for deleting rather than inserting a toplevel line.)

1. Click to put the cursor on a blank toplevel line.
2. Press backspace to delete the line.

Focus should still be on the toplevel cursor, but instead it is on a block.

**Comment by justinpombrio** [comment]
@schanzer Maybe this is one of the "interesting corner-cases where we need to be more sophisticated"? :-)

**Comment by schanzer** [comment]
Odd - I can't seem to reproduce this. Is this in Chrome? Firefox? Safari? Does the Delete key do the same thing? Maybe it's that my laptop doesn't have a proper backspace key...

**Comment by justinpombrio** [comment]
Oops, I was on a branch with an old version of master. Never mind, it's fixed on master.
