### ISSUE TITLE
Outdated drop targets

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#218]
1. Start with the program:

    (foo)
    (bar)
    (baz)

2. Go to block mode, and insert a newline after `foo`.
3. Double click to edit the drop target under `baz` and enter "bad".

The string "bad" appears under `bar` instead of `baz`!

**Comment by justinpombrio** [comment]
It looks like this issue existed since WIP-optimization was merged. (I'm surprised we didn't notice it before!)  This makes sense - while the AST is up to date, if a DT hasn't been re-rendered, it will still be holding onto its old source location.

**Comment by justinpombrio** [comment]
The issue is that the source location for a drop target, for example `location={this.name.from}`, becomes out of date when an edit far away inserts or deletes a line. I see a few ways to fix this, all of which are awful:

1. Update `this.name.from`. It's an object, so it has identity and can be mutated. The ast-patching algorithm could keep the same ast, and mutably update the `to` and `from` fields of each node. This would be brittle, though. For example, if a drop target had `location=somefunction(this.name.from)`, then mutably updating `this.name.from` wouldn't update the droptarget's location. I do NOT want to have to explain that in the language-api docs.

2. Make `location` a thunk, and have the ast-patching algorithm keep the same ast. For example, you'd have `location={() => this.name.from}`. The ast-patching algorithm would have updated the ast node `this.name`, so when that thunk is called it would get the latest `from` source location.

3. Re-render the drop target before it's edited. Except that doesn't quite make sense, as once the drop target has been constructed its location is fixed. So rather, re-render the `ASTNode` containing the drop target, sometime before the drop target is edited. If we proactively re-render *all* nodes after a line is inserted or deleted, that would do the trick but also be very inefficient. Alternatively, we could wait until a drop target is edited and then immediately (i) grab its containing `ASTNode`, (ii) re-render that `ASTNode`, and (iii) make the edit on the newly constructed drop target that has the correct source location. This would require linking each drop target to its containing `ASTNode`; currently there's no link between the two.

4. Maybe we can `mark` each drop target, and have codemirror deal with the source location changes? This would result in a lot of marks, many of which overlap: is that do-able?

**Comment by schanzer** [comment]
Option 2 seems like the approach with the fewest drawbacks. DropTargets are always defined in terms of their position relative to other nodes anyway, so in some sense it might make more sense to have location defined either as a thunk _or_ as two properties: `nodeSibling` (and ASTNode) and `position` (either `from` or `to`). At edit time, we either evaluate the thunk or we grab the position from the node.

**Comment by justinpombrio** [comment]
Fixed by #222.
