### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#219]
This is out of date now that `new-reactify` is `master`.

**Comment by schanzer** [comment]
Fixed in https://github.com/bootstrapworld/codemirror-blocks/commit/f080be3d4873e99282b8ba4ce16d9a1dedded698#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by prestontw** [comment]
This is still different than what I've been doing with code.pyret.org + CMB. CMB's constructor takes a container, not a CodeMirror instance.
