### ISSUE TITLE
Drag-and-Drop to toplevel is broken

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#226]
1) Load the editor and switch to block mode
2) Try to drag something to the top level (CM)

EXPECTED: the dragged block appears at the drop location
ACTUAL: we get a beep and a no-op.

I believe the culprit is https://github.com/bootstrapworld/codemirror-blocks/commit/a48639fa641635e4a93ae230f4901b486fb80b7d . This works in the previous commit.

I don't think that code that checks to see if there's a valid top-level drop does not belong inside the droptarget code.

**Comment by justinpombrio** [comment]
Another test case: drag the (commented) `if` after the (uncommented) `print`. If that's fixed, then the fix for it is probably contributing to this issue.

**Comment by justinpombrio** [comment]
@schanzer: after f82c43cb175cf3df77c7, I'm not seeing this issue anymore, though that commit wasn't trying to fix this, and it certainly didn't do what you suggested to fix this.

Could you check to see if you can replicate this bug anymore? (If you can, tell me exactly what actions to take on the big-standard-wescheme-example, and I'll look into it.)
