### ISSUE TITLE
Add a user-configurable toolbar

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#23]
Support an API for displaying language primitives in a configurable toolbar:
- [x] given a list of strings, display them in alpha-sorted order
- [x] given a list of function descriptor objects, display them in alpha-sorted order
- [x] given either of the above and a sorting function, display them in sorted+grouped order
- [x] blocks dragged to the trash should be deleted
- [ ] hovering over a primitive should show a sample block, using all available data from the language primitives

See spec at https://docs.google.com/document/d/145i-a2FA8UMASCqUnP6CC5C-mWtrGUy4kEfp1lowN6s/edit#heading=h.njv3u2cfywxj

**Comment by pcardune** [comment]
Working on this in the following branch: https://github.com/bootstrapworld/codemirror-blocks/tree/toolbar

**Comment by pcardune** [comment]
@schanzer is there a good example of what the list of primitives would be for your use case?

**Comment by schanzer** [comment]
Added a (non-exhaustive) list to the bottom of the language spec.

**Comment by pcardune** [comment]
@schanzer: How important do you think it is for hovering over a primitive to show an example block? Right now you can click on the primitive to see an example block. Then you can drag the example block over. Is that good enough?

**Comment by schanzer** [comment]
As long as the primitive itself can be dragged as well, I'm cool with it :)
