### ISSUE TITLE
Make toolbar accessible 

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#235]
Down-arrow from the searchbox should select the first primitive in the list (should mimic browser search)

**Comment by justinpombrio** [comment]
I missed the big picture: this needs to actually focus something so that you can copy the node. Ideally: focus name & tab refocused onto node.

**Comment by justinpombrio** [comment]
Bug: up/down shouldn't scroll

**Comment by justinpombrio** [comment]
TODO:
- [ ] up/down shouldn't scroll
- [ ] tab should select block
- [ ] "Cannot update during an existing state transition" warning on first blur
