### ISSUE TITLE
Get comment tests to pass

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#243]
Fix the comment tests in `spec/comment-test-incomplete.js`.

------

In the past, sometimes editing/dragging/pasting a commented node, or a node surrounded by commented nodes, would "leak" some of the comments. See, for example, issue #176.

To prevent regressions, it would be good to have test cases that make sure this no longer happens. These test cases exist, in `spec/comment-test-incomplete.js`, but they fail for mysterious reasons. This issue is to fix those tests. (To be clear, CMB currently _behaves_ correctly, and comments do not leak. Thus the comment tests _should_ pass, but they fail for unknown reasons.)

**Comment by schanzer** [comment]
2 of the 3 tests here use the paste event, which can't really be simulated due to browser security restrictions. They'll need to be rewritten as drag/drop - or maybe change? - events.

**Comment by schanzer** [comment]
Closed by 53997cd9f7d9339f0691c5a7c5f7b1ecaa0b277d
