### ISSUE TITLE
Simplify addLanguage API

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#245]
There are some pretty straightforward ways that the language API could be made simpler. Right now, things are set up as if we would have lots of configuration---like multiple render options, and a parser with several methods on it---but we don't, so it feels like overkill. `addLanguage()` is the first thing a potential language author sees, so it should be minimal:

- [x] Remove `getRenderOptions()`. Instead, have each `ASTNode` say whether it's locked or not (perhaps by setting `this.isLocked = true;` in the constructor if it is).
- [x] Consider replacing the `getParser()` function (which returns an object that contains a `.parse()` method) with the `parse()` function directly.
- [x] We should have a generic, wrapper `getExceptionMessage` function, in case the provided parser doesn't implement a good one.
- [x] Eliminate `ASTNode.options["aria-label"]` in favor of `shortDescription()`.
- [x] Update the docs (docs/language.md) to match.

**Comment by justinpombrio** [comment]
I think that making these changes could be a good way for someone new to see a few parts of the code base.

**Comment by schanzer** [comment]
Closed by d79215a1ac2d4cca56debbeb8dbc481c600a2f07, 63404c9e4f1ab40bf27f8548531df54f6e44067e, fb8d0f9ca01a510fe2d3a4924ec74c50353bad25, 5de52abb478cbc0567ffcbcbc6f30d44855df05d, 6a60e053d1892db4b9f97518883a86b95e54887b
