### ISSUE TITLE
Unable to add parameter at end of lambda-list

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/codemirror-blocks#263]
```
(define (eksample x y)
  (+ x y))
```

In blocks mode, I'm able to insert a new lambda-parameter (say `z`) before `x` and between `x` and `y`, but not after `y`.  (A workaround is to insert the new parameter _before_ `y` and then interchange names, but that's a burden.)

**Comment by schanzer** [comment]
I can't re-create this in the interactive example at `npm run start`.

**Comment by schanzer** [comment]
Ah, the problem shows up on WeScheme. And surprise, surprise - it's because I monkeypatched the global Array object in the WeScheme compiler. This is really a bug in WeScheme, but I'll see if I can do a quick workaround in CMB for now. Thanks!
