### ISSUE TITLE
blanks do not behave as expected across edits

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/codemirror-blocks#273]
Start with `( )`
Click run
Remove the `...` from the function position
Click run

**Comment by schanzer** [comment]
@jpolitz deleting required fields is now no longer possible. I believe this is now fixed, but if you want to [try it out to sure](https://blocks-dot-wescheme-hrd-2.appspot.com/openEditor?definitionsText=(%20)) it would be a huge help!

**Comment by jpolitz** [comment]
I don't think the now-current behavior is a problem, though it lets me delete what's behind the `?` to get a different error.

![Mar-31-2021 20-59-00](https://user-images.githubusercontent.com/119891/113241815-465fcb00-9264-11eb-84e3-871850c61686.gif)

**Comment by schanzer** [comment]
Thanks! That's better, but not where it should be. I'll keep looking into it...

**Comment by schanzer** [comment]
Aha! Looks like an invariant wasn't being obeyed, nor was there any user feedback about attempts to break it. Fixed both, and updated [WeScheme](https://blocks-dot-wescheme-hrd-2.appspot.com/openEditor?definitionsText=(%20)) to match.
