### ISSUE TITLE
toolbar scrolling is wonky

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/codemirror-blocks#276]
For a short editor window, clicking on a primitive at the bottom of the toolbar will scroll it up, hiding the primitive

**Comment by schanzer** [comment]
This is now fixed on the `fix-276` branch, but it's exposed a different bug in how we deal with setCursor. I'll close this when the other bug is stomped.

**Comment by schanzer** [comment]
@jpolitz , when you have a moment -- can you check out [https://bootstrapworld.org/preview/sina/new-editor.html](https://bootstrapworld.org/preview/sina/new-editor.html)  and tell me if the toolbar scrolling is fixed?
