### ISSUE TITLE
Event handlers are not preserved across mode switch

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/codemirror-blocks#277]
`(define f (x) (+ 1 2))` creates a parse error, with blocks being colored

Fixing the error does NOT remove the color on the body of the function. Console logging shows that location information was lost

ALSO: markers need to be cleared *when codemirror clears them*, meaning we should re-sync after _every edit_

**Comment by schanzer** [comment]
@jpolitz this is in the blocks-enabled WeScheme, right? I want to confirm that this is an issue of how we implement the CM API, vs. an error in how we manage state internally.

**Comment by jpolitz** [comment]
Based on the date of submitting this, I think it was at an all-hands meeting. There was a followup from you on Oct 15 about that testing session on email. So it's with whatever link we were testing at that time.

**Comment by schanzer** [comment]
Ah! That helps. Thanks!

**Comment by schanzer** [comment]
WeScheme makes a bunch of calls to MarkText, storing the results. Then, when the editor changes, it loops through them and calls `marker.clear()`. For native CM textmarkers this works. But our BlockMarkers don't.

**Comment by schanzer** [comment]
Yet more state that is not preserved across mode switch: `on` and `off` event handlers. When embedded in WeScheme, for example, the `CM.on('change', function() { ....clear all markers... })` handler gets lost when switching to block mode.
