### ISSUE TITLE
What is the list of release blocking nodes?

### ISSUE THREAD

**Issue by MadeofTin** [bootstrapworld/codemirror-blocks#32]
@shriram,

I am testing some UX design concepts for the blocks themselves. We have a few nodes already supported in `ast.js`, and we could support many more then we need for the first release. But, do you have a sense of which ones we would need for launch? It would be helpful for me as I make mock ups.

Cheers,
James

**Comment by shriram** [comment]
Hi James. The idea was this language would support the Circles of Evaluation visual concept that @schanzer has spent years developing. So let's also make sure that he's in on the design and signs off on them.

By “which ones” do you mean which operators?

**Comment by MadeofTin** [comment]
Exactly, I am trying to get the requirements for the circles of evaluation.
I want to make sure it is in line with his vision.

**Comment by schanzer** [comment]
For launch, we need the language specified in the last section of this doc:
https://docs.google.com/document/d/145i-a2FA8UMASCqUnP6CC5C-mWtrGUy4kEfp1lowN6s/edit?usp=sharing

**Comment by MadeofTin** [comment]
Yes thank you, I hadn't seen that before. I am going through the program
now to get a feel for it then will dive into this.

**Comment by schanzer** [comment]
Honestly, there's very little blocking release on the AST node end. It's more about features like accessibility, touch-event support for tablets, etc. 

I'm going to close this issue for now, but feel free to re-open if you have a specific question about the AST.
