### ISSUE TITLE
Build project website

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#34]
We need a good project website that includes documentation, tutorial, working examples, and some basic marketing.
- [x] Stub out basic website structure
- [ ] Integrate examples directory into the website
- [ ] Generate documentation from source and host on website
- [ ] Write marketing copy
- [ ] Implement a cool design

**Comment by pcardune** [comment]
See #42 where I got a jekyll site up and running.

**Comment by pcardune** [comment]
Perhaps we should consider using http://readme.io?

**Comment by shriram** [comment]
Just fyi, for the Pyret side of things we use Scribble [http://docs.racket-lang.org/scribble/]. It's not beautiful output, though much of that could be addressed by layering on a bunch of CSS and maybe JS. But it is a really great bit of language design [https://www.cs.utah.edu/plt/publications/icfp09-fbf.pdf] that makes a lot of things go much more smoothly than in most other markup/down languages.

**Comment by schanzer** [comment]
I'm not sure we really need a website for this. It's a highly developer-focused project (the only people who would want such a thing are going to have to be comfortable working with parsers!), and the GitHub ReadMe goes into all the developer details.
