### ISSUE TITLE
Create full featured scheme rendering example

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#35]
In the current wescheme example, we hide several node types that are actually supported by the AST and the renderer, since we are using this example to see how things would look inside bootstrap.

We should create another example that shows off all the available node types and renderers.

**Comment by schanzer** [comment]
Fixed in the full-scheme branch, by https://github.com/bootstrapworld/codemirror-blocks/commit/fa1d331f095dc974edb4301f94941743b0d66e24

I suspect we'll want to add more node types, since this is a trivial demo?
