### ISSUE TITLE
Quarantine-using tests are not reliable

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/codemirror-blocks#353]
`spec/comment-test.js` and `spec/new-blocks-test.js` fail showing string comparison failure involving anomalous newline character. May not be strictly reproducible. Apparently introduced in 53997cd.

In current commit (80562fd), new-blocks-test.js is OK in one run. In another, it fails for the tests for typing at the (1) beginning, and (2) end of a line.

comment-test.js failures can be temporarily quieted by commenting out the tests for inserting commented node after (1) commented node, and (2) uncommented node.

**Comment by schanzer** [comment]
Apparently the changes introduced in 53997cd9f7d9339f0691c5a7c5f7b1ecaa0b277d weren't enough to turn those tests back on. Will investigate...

**Comment by schanzer** [comment]
Fixed by fe6dd36df0641e4dc4c305d515a0ce7bbfc4cc04
