### ISSUE TITLE
Website is currently broken

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#362]
The website at https://bootstrapworld.github.io/codemirror-blocks/ is currently in a rather broken state. Here's a list of things that don't work:

1. Loading the front page throws a bunch of errors in the console about requests for external resources being blocked
2. The "Toggle Block Button" in the JSFiddle example doesn't do anything (except throw errors in the console)
3. The "Read the Docs" link 404s
4. The "Talk to Us" link goes to a gitter chat room that's been inactive since 2016

After clicking on the [Examples link](https://bootstrapworld.github.io/codemirror-blocks/examples/) in the header:

5. The codemirror-blocks link in the header 404s
6. `(define)` blocks in [the wescheme example](https://bootstrapworld.github.io/codemirror-blocks/examples/wescheme.html) don't show up
7. All the example pages spew react error messages like: `Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state...`

From what I can tell, the website hasn't actually been updated since 2017, as that was the last time the [gh-pages branch](https://github.com/bootstrapworld/codemirror-blocks/tree/gh-pages) was pushed to. So the build script and continuous integration for the website is probably also broken.

We need to either:
1. fix the website and the mechanism by which it gets updated, or
2. delete the website altogether since it doesn't seem to be serving any purpose

I'd vote for option 2. What do you think @schanzer?

**Comment by schanzer** [comment]
I'd vote for option 2. There will likely be a need for it _in the future_, but I don't think maintaining it right now is the best use of your time.

**Comment by pcardune** [comment]
I think deleting the website would involve doing the following:

- delete the `site` directory in the repository root
- delete the `deploy-example.sh` and `deploy-ghpages.sh` scripts in the repo route
- Delete the `after_success:` step in the [travis config](https://github.com/bootstrapworld/codemirror-blocks/blob/master/.travis.yml#L40)

Questions:

- Should I also delete the `example/` directory or is that useful for local development?
- What's up with the heroku related files (`heroku-server.js`, `Procfile`)? Can I delete those too?

**Comment by schanzer** [comment]
1) `example/` is _definitely_ useful for development
2) those files are left over from when you first wrote them :) I don't think we're actively using heroku right now, so feel free to delete
