### ISSUE TITLE
API is undocumented, incorrectly documented, inconsistently applied, and probably broken. Migrate to typescript?

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#368]
I started encountering these problems while trying to implement a new language package from scratch.

For example, to add a language, you need to call `addLanguage(languageDefinition)`. Some runtime checks are performed to make sure that `languageDefinition` contains certain "required" fields like `id`, `name`, and `parse`, and supplies defaults for some other fields that are "not required" like `getExceptionMessage`. However, the internal code expects there to be more stuff on there, like `primitivesFn`. Some [old docs](https://github.com/bootstrapworld/codemirror-blocks/blob/master/doc/language.md) refer to `primitivesFn` as an optional field, for which defaults will be provided, but later, the [ToggleEditor component expects it to be present](https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/ui/ToggleEditor.js#L240), leading to an obscure looking runtime exception.

The solution is to a) carefully document to the APIs that language module authors are expected to use, and b) actually adhere to those APIs in the code base. We can kill two birds with one stone by just using typescript. I see that there is already a typescript config in the repo but only one .ts file (that doesn't actually specify any explicit types).

Is there any reason why more stuff hasn't been moved to typescript or is it just a question of not enough time to do the work?

**Comment by schanzer** [comment]
Ooooof. That's embarrassing. It's a question of time and my own skillset: I can _read_ typescript, but I don't feel super confident _writing_  it. So the end result is that I wind up avoiding it more than I should (and never getting the practice to get faster...).

Moving everything over to TS would be awesome, but I don't have even close to the bandwidth to do it. We've used it in the mission-critical `ast` file, but clearly it should be used everywhere else, too. 

If bringing order to the world via typescript is something you enjoy doing (it is for me, in other typed languages!), this would be a fantastic contribution!

**Comment by pcardune** [comment]
> If bringing order to the world via typescript is something you enjoy doing (it is for me, in other typed languages!), this would be a fantastic contribution!

Moving things to typescript makes me feel like Bob Ross, except the "happy little accidents" get crushed with perfect corrections. It's basically my happy place. I will go ahead and assign this to myself as well.

**Comment by schanzer** [comment]
@pcardune Did you have even grander ambitions than the recent PR, or does that merge address this issue?

**Comment by pcardune** [comment]
More PRs are coming. My plan is to try to add types and documentation for the entire public API.

**Comment by schanzer** [comment]
@pcardune curious about other files you plan to typescript-ify. Are you planning to hit every single JS file, or only a subset? As of now I think the only ones left are in the `ui/` folder.

**Comment by pcardune** [comment]
Yep, planning on doing everything.

**Comment by pcardune** [comment]
I think after the #387 gets merged, we can close this issue and I'll be ready to take on something new.

**Comment by schanzer** [comment]
Sorry, somehow I accidentally PR #388 into the wrong branch! Merged it in via a commit instead.
