### ISSUE TITLE
Write tutorial/documentation for creating your own parser + renderer and extending the AST

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#37]
We already have a basic example in the example directory, but it could get fleshed out more and have documentation and a tutorial written around it. I think it would be cool if we used the programming language described in the programming language tutorial: http://lisperator.net/pltut/

**Comment by schanzer** [comment]
This is sort of a subset of the work @justinpombrio is doing, so I'm assigning it to him for tracking purposes.

**Comment by justinpombrio** [comment]
Thanks @schanzer. Yes, this is definitely mine.

Here's the documentation I've written so far:

- [pretty printing](https://github.com/bootstrapworld/codemirror-blocks/blob/new-reactify-with-pretty/doc/pretty.md)
- [stylesheets](https://github.com/bootstrapworld/codemirror-blocks/blob/new-reactify-with-pretty/doc/stylesheet.md)
- [adding a language](https://github.com/bootstrapworld/codemirror-blocks/blob/new-reactify-with-pretty/doc/language.md)

And good idea, @pcardune. I like the idea of adding a _tutorial_, in addition to the documentation. Especially if it, as you suggest, it follows an existing "define a language in 5 hours"-style tutorial.

(These docs are all somewhat out of date; I think it'll be most efficient to leave them that way and once things are more stable do a single pass to bring them all up to date at once.)

**Comment by justinpombrio** [comment]
The docs are now reasonably complete, in the `merge-pyrets` branch. I'm closing this issue: if the docs are incomplete somewhere, we should open a specific issue for that.

https://github.com/bootstrapworld/codemirror-blocks/blob/merge-pyrets/doc/language.md
