### ISSUE TITLE
Make sure our HTML passes validation

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#373]
See https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.bootstrapworld.org%2Fmaterials%2Ffall2021%2Fen-us%2Fcourses%2Fdata-science%2Flessons%2Fsimple-datatypes%2Findex.shtml

- [ ] Javascript includes do not need `text/javascript`
- [ ] `<tt>` is deprecated
- [ ] `height=""` is invalid
- [ ] There's a closing `p` tag, but not an opening one
- [ ] IMG tags need alt text

**Comment by ds26gte** [comment]
I think this issue should be filed under the `curriculum` repo...?
