### ISSUE TITLE
log replay on example page is broken

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#375]
Steps to repro:
1. start development server with `npm run start`
2. go to http://localhost:8080/editor.html
3. click on the block icon to switch to blocks mode
4. edit the blocks however you like
5. click "Download Log"
6. reload the page
7. click "choose file" and load the log you just downloaded
8. click the ">>" button until you get to the first "SET_AST" step

The following error will show up in the console and nothing changes in the editor.

```
reducers.ts:117 Uncaught TypeError: Cannot read property 'getNodeById' of null
    at reducer (reducers.ts:117)
    at dispatch (redux.js:288)
    at Object.dispatch (index.js:11)
    at BlockEditor.executeAction (BlockEditor.tsx:381)
    at Object.executeAction (BlockEditor.tsx:456)
    at HTMLInputElement.nextButton.onclick (editor-example.js:87)
```

**Comment by pcardune** [comment]
I ran into this issue while trying to make sure I wasn't breaking anything when refactoring the example page to work better with #374. I'm wondering if I'm using this feature incorrectly or if maybe it's just hasn't been used in a while and broke at some point? If the latter, is it worth fixing?

**Comment by schanzer** [comment]
Ah, looks like this has bitrotted somewhat. I'll fix later today.
