### ISSUE TITLE
Refactor Sequence constructor

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#377]
Old interface: "give me a string!"
New interface: "give me a literal so I know where to put something that's dropped as the first child!"

The new interface makes parser code messier, since it has to construct the literal. This could be done in the Sequence constructor, restoring the old interface and letting parsers stay clean.

**Comment by schanzer** [comment]
@pcardune had a moment to sit down and think about this issue finally, and I'm of the opinion that the current behavior is actually required.

Sequences could be used for things like let- or begin- expressions in Schemelike languages, or just for a list of statements in more procedural languages. Only the language modules know whether there's a name field, and (more importantly) only the language module knows the location of that field. Consider this contrived example:

`(begin 1 2 3)`

In the Scheme example above, there's no way for CMB to infer that "begin" should start one character after the start of the whole expression. That means there's no way to construct the literal inside the `Sequence` constructor, and this complexity still needs to happen in the language module.

If you agree, I think we can just close this issue.

**Comment by pcardune** [comment]
I agree.
