### ISSUE TITLE
Improve test code coverage

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#38]
It kind of went down hill in the last couple months. We should try to get it back up to 90%+

**Comment by schanzer** [comment]
Should we leave this open as a general reminder, or close it now that we're at 88%?

**Comment by pcardune** [comment]
Let's leave it open a bit longer.

**Comment by pcardune** [comment]
I'm actually going to close this in favor of smaller issues for specific problem files.
