### ISSUE TITLE
Refactor calls to setTimeout() from inside react components to cleanup on unmount

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#394]
As evidenced in [this comment on heisen test failures](https://github.com/bootstrapworld/codemirror-blocks/issues/391#issuecomment-914529405) we are currently using `setTimeout()` incorrectly in react components.

We need to go through all of the uses of setTimeout in the codebase and ensure they are being properly cleaned up with `cancelTimeout()` when the components that created them are unmounted.

**Comment by schanzer** [comment]
Obviously this doesn't address the root cause of the issue, but just wanted to flag that I've gone through and replaced the majority of these calls with afterDOMUpdate - at the very least, this illuminates the guesswork involved in setting up the appropriate timeout delay.￼￼

It seems like the way to address this is to have ￼afterDOMUpdate automatically store the timeout somewhere that can be cleared when the component unmounts.￼￼ Should each editor instance maintain its own array of timeouts? If so,￼ how do we expose that to ￼afterDOMUpdate?

**Comment by pcardune** [comment]
Each component that calls setTimeout() should be responsible for cleaning up that timeout. It looks like this:

```ts
class MyComponent extends React.Component {
  pendingTimeout?: ReturnType<typeof setTimeout>;

  componentDidMount() {
    this.pendingTimeout = setTimeout(()=> {
      // do stuff later...
    });
  }
  componentWillUnmount() {
    clearTimeout(this.pendingTimeout);
  }

  render() {
    ...
  }
}
```

This is the simple case where your component has only one `setTimeout()` which is only called once during the entire lifecycle of the component. Everything gets more complicated when calling `setTimeout()` depends on the value of props, and the solution depends on the intended semantics.

Are you using setTimeout as a queue where every time the props change a new setTimeout() is executed? Then you want to store the handles in a list and cancel all of them in componentWillUnmount. You probably also want to remove them from the queue inside the callback so the queue doesn't end up with an infinite number of stale handles. But if the queue should only contain at most one item, as in the example above, then what do you do when there is a second set timeout before the first one has executed? You have to cancel the previous one and replace it with the new one in componentWillUpdate().

If you want the callback for the setTimeout to execute even after the component has been unmounted but you still want to be able to wait for all of those timeouts to finish before doing something else outside of react entirely, then you need some kind of global store. I am skeptical that there is anything in codemirror-blocks that should need to do this. This should only be needed for things like aggregating logs that will get sent to a remote server or similar "fire and forget" types of events.
