### ISSUE TITLE
Data flow issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#412]
- [x] Internal mutability of the AST (specifically the `element` property)
- [x] In PrimitiveList.tsx, we mutate the `primitive` prop ([more info](https://github.com/bootstrapworld/codemirror-blocks/pull/410#discussion_r713507175))
- [x] Investigate `element` prop in Toolbar.tsx ([more info](https://github.com/bootstrapworld/codemirror-blocks/pull/410#discussion_r714116240))
- [x] Remaining properties of `SHARED`

**Comment by schanzer** [comment]
Sorry, I meant the specific issues listed above. I'll add these to the top as well.

**Comment by schanzer** [comment]
@pcardune I'm happy to tackle the final checkbox item listed here, but I'm not sure I see a clean way to do it. The only way I can think of to avoid mutating the `element` property of the tree is to have a separate mapping from a node's `id` to its `element`, and let the mapping get mutated.

But the tree still needs to be mutated in the `unify` function, so we're still not off the hook. And now the mapping _also_ need to be mutated. Did you have something else in mind?

**Comment by pcardune** [comment]
I have some ideas for this, but I need to noodle with them a bit. I'll go ahead and assign this task to myself for the last part.
