### ISSUE TITLE
Modernize wescheme-js code base

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#43]
It needs a lot of love to upgrade old-style javascript to ECMAScript 6, not to mention have proper unit tests written for it.

The most important parts are the lexer, parser, and analyzer. The rest will eventually get deprecated in favor of just using the pyret runtime under the covers.

**Comment by schanzer** [comment]
Are the existing unit tests improper because they're not using Karma? They're awfully thorough, and it would be great to use them.

**Comment by pcardune** [comment]
regarding tests, I think the biggest problem is that coverage is only 51% :(

The other issue with the tests is that they aren't really unit tests, they are functional tests. Every test is basically testing the whole thing. If you break something, you'll probably end up getting a bunch of test failures that don't actually describe what it is that you broke. It will just say that your code doesn't properly handle test # N, which isn't very helpful.

The existing tests are great for high level regression detection, but they aren't really a good foundation for continued development IMO, which maybe isn't a big deal since there aren't really big features that need to be added...

As for modernization, I haven't taken a look at your recent changes, so hopefully there is less work to do. I still see files with big (function() { })() closure blocks which are unnecessary. Also the module layout is pretty funky, with some modules effectively monkey patching other modules, which is cray cray. Like the following pattern:
```
var somemodule = require('somemodule');
somemodule.monkeypatch = 'foo';
```
is a pretty big code smell.

**Comment by schanzer** [comment]
Makes sense. I'm torn about the monkeypatching -- the alternatives are either:
1. Use a visitor pattern for each phase of the compiler, which performs poorly relative to the current solution
2. Have a separate file for each AST node type, with all the functionality laid out in that file. Seems like too many files to me, but I don't have a good sense for this sort of thing.
3. Combine parser.js, analyzer.js and structures.js files into a single file. Seems like too big a file to me, but I don't have a good sense for this sort of thing.

Solution 3 might be reasonable, considering that we're dropping the bytecode generation soon anyway. What do you suggest?

As for unit tests - this code isn't going to change anytime soon. Allowing comments to pass through to the parser is the only thing on our roadmap, and that's a pretty small change. And whether that's done or not, this stuff is going to sit in cold storage for a long, long time. Given that this code has been battle-tested by tens of thousands of users for the last two years, I have a lot of confidence in its correctness.

**Comment by pcardune** [comment]
What does "performs poorly" mean? Like actual compute time? That would surprise me. I need to understand the code a bit better before I can give a good suggestion.

**Comment by schanzer** [comment]
instanceof checks are much more expensive than having each subclass dispatch on it's own method, but I guess it's stupid to worry about performance in this context. Obviously it'll be fast enough: if I'm being honest, I think I'm just reticent about digging back into a codebase that already works so well! But I guess that's the very thing I'm trying to teach students, soooooo I'll get stared. :)

**Comment by pcardune** [comment]
You could use something other than an instanceof check... Like have each
structure specify a type string and use that in a Map to do lookups. I
think instanceof is expensive because it walks the inheritance chain, but
you probably don't need inheritance logic right?

**Comment by schanzer** [comment]
Just pushed updates to wescheme-js. Test suite continues to pass. Changes:

1. use the visitor patter in the analyzer (ignoring the bytecode generator, since it's going away when we switch to Spyret)
2. use fat-arrow notation everywhere
3. get rid of (function() { })()
4. backport an improvement from mainline wescheme that fails more gracefully if there are errors when loading remote modules

(Honestly, though, the only functionality we're _actually_ using from this module is the lexer, right?)
