### ISSUE TITLE
Is an accurate representation of how the Abstract Syntax Tree fits?

### ISSUE THREAD

**Issue by MadeofTin** [bootstrapworld/codemirror-blocks#44]
![ast](https://cloud.githubusercontent.com/assets/1226869/13060149/3e2a36da-d3e4-11e5-9e6f-d2f2f150835a.png)

@pcardune 
#question

**Comment by MadeofTin** [comment]
I should note my end goal is to make something like Docker's "The Docker Solution" to for documentation and the website.

![screenshot at feb 15 13-33-02](https://cloud.githubusercontent.com/assets/1226869/13060785/c2a87346-d3e8-11e5-81a3-911b1cf9aa09.png)

**Comment by pcardune** [comment]
Look right to me!

**Comment by schanzer** [comment]
How about "code", instead of scheme? We're not really teaching scheme here, and I'd rather be as accurate as possible
