### ISSUE TITLE
Figure out method for deploying changes to blocks.wescheme.org

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#480]
The current plan is for blocks.wescheme.org to load a bundled version of the wescheme-blocks package from some CDN url that we can change without having to deploy new versions of `blocks.wescheme.org`.

There are a few ways we could do this:
1. publish actual npm packages for wescheme-blocks that includes a bundled version of itself, and then point blocks.wescheme.org to the bundled file via unpkg.com.
   - pros: This is precisely how a number of libraries (including react) make bundled versions of their library available without having to npm install anything. The bundling would happen automatically along side the rest of the release process.
   - cons: Without making assumptions about the environment the bundle would execute in, it would have to include all its dependencies, including react and the relevant code from wescheme-js. This would make the bundle very (prohibitively?) large. wescheme.org already includes all of wescheme-js, so there would be duplicate code being downloaded. We could make a wescheme.org specific bundle that excludes dependencies that are already available on wescheme.org, but then the bundle would be unusable in any other environment.
2. create a specially crafted bundle file for wescheme.org that's optimized to run in wescheme.org's environment, and commit it to this repository. blocks.wescheme.org would then point to a url like https://raw.githubusercontent.com/bootstrapworld/codemirror-blocks/master/packages/wescheme-blocks/dist/wescheme.org.bundle.js
   - pros: This wouldn't require any special release process other than committing to the repository. The urls could still be versioned via branch names, commit hash, or tag name.
   - cons: In theory, any change to the repository would require that a new bundle be created to make sure that the bundle is an accurate reflection of the code in the repository at that point in time. This would make the git history potentially bloated and checkouts would take longer. Some projects commit build artifacts to the repository despite this downside, so maybe it's not that bad.
3. same as 2, but instead of committing the bundle to this repository, we'd stick it somewhere else.
    - pros: don't need to worry about the cons from 1. or 2.
    - cons: we would need to come up with some other storage place. Either a different git repository, or some file hosting service.
4. Don't make bundling part of this repo, and instead just do the special bundling in the wescheme.org repo, saving the bundle with the rest of the bundle files in wescheme.org. blocks.wescheme.org could still point to the bundled file directly via the github url so we don't have to deploy a whole new version of the site.
    - pros: this is how production bundling should work long term.
    - cons: its a bit more of a manual process since something in wescheme.org would have to do the bundling whenever a new version of wescheme-blocks is available.

@schanzer, do you have any thoughts about the above? Long term, I don't think it makes sense for any of the packages in this repo to provide bundles, since there are a lot of shared dependencies and any optimization depends on the runtime environment. Bundling is best done at the application layer where there's enough information to do proper optimization.

**Comment by schanzer** [comment]
Can't we have github actions run `npm run build`, and stick the resulting JS bundle on a github-hosted website? I could have sworn you had something like this running when you first started up the repo, years ago.

**Comment by pcardune** [comment]
yay!
