### ISSUE TITLE
Setup/deploy blocks.wescheme.org

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#481]
Not sure what steps are required to do this but it should:

- deploy a branch of the wescheme.org repo that uses a bundled version of wescheme-blocks (depends on #480)
- make sure authentication works exactly the same as wescheme.org

**Comment by schanzer** [comment]
@pcardune anything else we need to do here?

**Comment by pcardune** [comment]
I guess not. Will close.
