### ISSUE TITLE
Fix or remove toggle button animation

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#484]
Similar to #483, the button to toggle between text and block mode currently expands/contracts when you hover over it. But sometimes the text that shows up disappears. Also, after you click on it, it stays expanded after you move your mouse out of it, which is confusing because before clicking, moving your mouse away will collapse it.

I think we should drop the animation and have the button always be the full size with the text or collapsed without the text.

**Comment by schanzer** [comment]
This was a painful compromise I reached with Sina. I'm comfortable punting on it, and (1) removing the animation and (2) hiding the text.

**Comment by pcardune** [comment]
`npm run start` builds off of the contents of the `/lib` directory, so it is correct that you need to build before `npm run start`. I usually have one terminal with `npm run build-watch` and another with `npm run start` so the changes propagate as a soon as I save them.

If you try to run `npm run build` or `npm run start` at the repository root, it should complain about "missing script" since those aren't defined in the top-level package.json. So you should run both of those commands in the packages/codemirror-blocks directory or with `--workspace=codemirror-blocks`.

Also, if you just run `npm run build` once, and then `npm run start`, any changes you make won't propagate until you run `npm run build` again, hence the `npm run build-watch`
