### ISSUE TITLE
Don't render definitions or comments in block mode

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#5]
Everything that's visible on the "canvas" must evaluate to something. Definitions and Comments do not.

**Comment by pcardune** [comment]
I'm going to say that the rest of this depends on bootstrapworld/wescheme-js#7 being completed, which I've assigned to you @schanzer.

**Comment by schanzer** [comment]
Added

**Comment by schanzer** [comment]
Complete. All tests passing.
