### ISSUE TITLE
Copy/Cut/Paste

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#7]
When a value is selected, standard cut/copy/paste operations should work.

**Comment by pcardune** [comment]
do they need to work outside the context of the codemirror editor? i.e. should I be able to copy a block, then open some other text editor and paste the block into it?

**Comment by schanzer** [comment]
Copying a block should copy the text representation to the clipboard. And yes, it should work between instances. This is implemented in the block prototype, at https://github.com/bootstrapworld/wescheme2012/blob/33adf7252c4c0007cc5fc8dcc27d080b944cab25/war-src/js/compiler/annotateCircles.js#L79-L90
