### ISSUE TITLE
Undo/Redo don't work when block is selected

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#8]
It looks like selected blocks capture ALL key events, preventing undo/redo from firing on the containing CM instance.

**Comment by pcardune** [comment]
this is a bit tricky. Codemirror's key down event handler is only registered for the textarea, which it looks like code mirror carefully moves around on the screen as you navigate the cursor around. The block elements are not children of the textarea, so keydown events on them do not bubble up to the textarea and don't trigger codemirror's key down handler.

**Comment by schanzer** [comment]
I see your point, and I'm certainly sympathetic - especially since not using the browser's native selection means that screen readers can't follow the tab key, which is a significant tradeoff to make. 

Would it be possible to listen for these events in the block keyhandler, and then call cm.undo() and cm.redo() instead?
